### ISSUE TITLE
Improve Mailer Texts

### ISSUE THREAD

**Issue by bkleinen** [modulehandbook/modulehandbook#165]
1.  Mail an Admins: hier muss der richtige server rein! (ggfs. Auch localhost!)

xxx has registered to join your site!

An admin can approve this registration by visiting the website and editing the user

[module-handbook.f4.htw-berlin.de](x-webdoc://F47634CA-0A22-4B7F-9C04-930B61D2FE3D/module-handbook.f4.htw-berlin.de)

2. wenn email noch nciht bestätigt ist, sollte dieser Text entsprechend ersetzt werden: 
You have signed up successfully but your account has not been approved by your administrator yet
(möglicherweise muss man hierzu auch tiefer in die devise config reingreifen)

**Comment by flashwing-04** [comment]
fixes https://github.com/modulehandbook/modulehandbook/commit/17dfe0f20641aadf33cd0f01f5af6d03e4f8ff89
